name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump'
        required: true
        type: choice
        options:
        - major
        - minor
        - patch
        - premajor
        - preminor
        - prepatch
        - prerelease

jobs:
  bump:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.bump.outputs.version }}

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.RELEASE_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.4'

    - name: Install poetry
      run: |
        python -m pip install -U pip
        pip install poetry 
    - name: Bump version
      id: bump
      run: |
        poetry version ${{ inputs.version }}
        version=v`poetry version -s`
        echo "::set-output name=version::$version"
    - name: Commit, tag, and push
      run: |
        git config --global user.email "kyle@leblanc.sh"
        git config --global user.name "Kyle LeBlanc"
        git add pyproject.toml
        git commit -m "build: release ${{ steps.bump.outputs.version }}"
        git tag -a "${{ steps.bump.outputs.version }}" -m "Release ${{ steps.bump.outputs.version }}"
        git push origin master --tags

  release:
    needs: bump
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: master

    - uses: ncipollo/release-action@v1
      with:
        name: Reef ${{ needs.bump.outputs.version }}
        generateReleaseNotes: true
        prerelease: ${{ contains(needs.bump.outputs.version, 'a') }}
        tag: ${{ needs.bump.outputs.version }}
        token: ${{ secrets.RELEASE_TOKEN }}