name: Bundle

on:
  release:
    types: [published]

jobs:
  build-docker:
    needs: upload
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2

      - name: 'Remove existing Docker context'
        continue-on-error: true
        run: docker context rm -f builders

      - name: 'Setup Docker Context'
        run: docker context create builders

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_TOKEN }}

      - name: 'Build and push workflow'
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v3
        with:
          file: './docker/Dockerfile'
          push: true
          tags: |
            ghcr.io/leblanck/reef:${{ inputs.version }}
            ghcr.io/leblanck/reef:latest
      - name: 'Build and push release'
        if: github.event_name == 'release'
        uses: docker/build-push-action@v3
        with:
          file: './docker/Dockerfile'
          push: true
          tags: |
            ghcr.io/leblanck/reef/:${{ github.event.release.tag_name }}
            ghcr.io/leblanck/reef:latest